### ISSUE TITLE
ReferenceError: CodeMirror is not defined

### ISSUE THREAD

**Issue by vindarel** [inaimathi/cl-notebook#10]
Hello,

I'm trying the cl-notebook from a local clone. After a quickload and running the main function as documented, I get a bunch of 404 errors for everything under `/static/` and finally `ReferenceError: CodeMirror is not defined`.

Is there another step required to run the notebook ?

Regards

(ps: I couldn't either run the binary on my Debian 64 but that's another thing)

**Comment by inaimathi** [comment]
Pardon the delay.

Reproed locally; it looks like this is an issue with handling static files from a `quickload`ed instance of `cl-notebook`. Gimme a minute.

**Comment by inaimathi** [comment]
Should be resolved as of https://github.com/inaimathi/cl-notebook/commit/d415d6ceaf4c9b8c5803f111f0dad81541bfb49b

**Comment by vindarel** [comment]
The error is now different, it can not load files in `static/js` and I get a TypeError in the config.ts:

```
Échec du chargement pour l’élément <script> dont la source est « http://localhost:4242/static/js/Blob.js ».
localhost:4242:12
Échec du chargement pour l’élément <script> dont la source est « http://localhost:4242/static/js/FileSaver.js ».
localhost:4242:13
TypeError: can't convert undefined to object config.ts:301:34
[… lots of static/js files]
ReferenceError: CodeMirror is not defined
```

    GET css/notebook.css 

is ok 

Firefox 58.

**Comment by inaimathi** [comment]
Can you tell if those static files exist? As in, do you see something on-filesystem at `~/.cl-notebook/static/js/`?

Also, could you try running `main-dev` instead of `main`? (That should point the static file system at your `cl-notebook` repo directory instead of the external statics directory.

**Comment by vindarel** [comment]
The files exist. 

oops of course, with `main-dev` they are loaded, and

```
[…]
GET
http://localhost:4242/js/notebook-addons.js
GET
http://localhost:4242/static/img/dots.png
[HTTP/1.1 200 OK 160ms]
TypeError: getPageHash(...) is undefined
[En savoir plus]
core.js:47:20
TypeError: can't convert undefined to object
config.ts:301:34
GETXHR
http://localhost:4242/cl-notebook/source
GETXHR
http://localhost:4242/cl-notebook/loaded-books?
[HTTP/1.1 200 OK 47ms]
Stream OPENED!
base.js:350:16
TypeError: dat is null
[En savoir plus]
core.js:562:34
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
[En savoir plus]
base.js:268:12
GET
http://localhost:4242/static/css/codemirror.css
[HTTP/1.1 200 OK 0ms]
GET
http://localhost:4242/css/notebook.css
[…]
```
(this tsconfig stuff may come from a FF extension)

I can see the `~/.cl-notebook/static/` directory with nothing inside.

**Comment by inaimathi** [comment]
In terms of the console errors, the worrysome one there is `getPageHash(...) is undefined`, because that kind of implies that `base.js` isn't being loaded early enough. (Although you do see the `Stream OPENED!` message furhter down.) Can you tell me what your line `350` is in `base.js`? Also, could you attach a screenshot of what the result of this is?

Pushed a commit to populate an empty `~/.cl-notebook/static/` directory. But you should be able to do `rmdir ~/.cl-notebook/static/` before starting `cl-notebook` in a fresh Lisp session to get those files populated (at that point, you'd be able to run with `main`)

**Comment by vindarel** [comment]
line 350 of base.js is the "STREAM OPEN!" log:

```
function eventSource(uri, bindings) {
    var stream = new EventSource(uri);
    stream.onopen = function (e) {
        return console.log('Stream OPENED!');
    };
```

I had a blank screen with a few buttons at the bottom:

![selection_223](https://user-images.githubusercontent.com/3721004/37825604-bc591de2-2e90-11e8-8c7c-49a1c23224c5.png)

Before the next test, how do I stop the running thread of `main-dev` ?

I see

```
(bt:all-threads)
(#<SB-THREAD:THREAD "Anonymous thread" RUNNING {10079D38E3}>
 #<SB-THREAD:THREAD "repl-thread" RUNNING {1004E380B3}>
 #<SB-THREAD:THREAD "auto-flush-thread" RUNNING {1004E37DF3}>
 #<SB-THREAD:THREAD "swank-indentation-cache-thread" RUNNING {10076C8323}>
 #<SB-THREAD:THREAD "reader-thread" RUNNING {10076C8153}>
 #<SB-THREAD:THREAD "control-thread" RUNNING {10076C2333}>
 #<SB-THREAD:THREAD "Swank Sentinel" RUNNING {10074041A3}>
 #<SB-THREAD:THREAD "main thread" RUNNING {10039CEF13}>)
```

It is the first Anonymous thread I suppose ?

**Comment by inaimathi** [comment]
Yup; you can `destroy` the first thread. `main-dev` does return the thread it spawns, so you could assign it somewhere locally and kill it later. (The intention is to spawn a `cl-notebook` while not monopolizing the REPL with its output).

That's actually a working instance, by the way. There's some known errors in `console`, but I don't think any of them blow up anything serious. (The latest commit fixes some, but I'll be plonking away at those for a while, I get the feeling).
