### ISSUE TITLE
BUGFIX: Line 55 in main.lisp

### ISSUE THREAD

**Issue by silent-entertainment** [inaimathi/cl-notebook#73]
(ql:quickload :cl-notebook) failed at qlot:install-quicklisp at line 55 in src/main.lisp.

#:install-quicklisp is not exported from #:qlot.
#:install-quicklisp is exported from #:qlot/install/quicklisp

Maybe it was refactored upstream in qlot.

    (unless (dir-exists? *ql*) (qlot:install-quicklisp *ql*))

needs to be changed to_

    (unless (dir-exists? *ql*) (qlot/install/quicklisp:install-quicklisp *ql*))

After changing the package identifier, (ql:quickload :cl-notebook) succeeded.

**Comment by silent-entertainment** [comment]
NOTE: Since cl-notebook isn't in the quicklisp repository due to its status, I added the local directory to an initialization file (adding the line (:directory "/home/luser/local-directory-to-cl-notebook/") to ~/.config/common-lisp/source-registry.conf.d/50-luser-lisp.conf per the asdf manual,  section 4.1) as a workaround to explore cl-notebook.

**Comment by inaimathi** [comment]
Dammit; sorry about the delay. I've been preoccupied with work :/

I see the `qlot` change; modified with the new symbol. I can't see where `cl-notebook` was removed from `quicklisp` repo (though I don't see it in the `ql:system-list`. Mind pointing me where I could find out more about that and how to resolve it?

Oh, also, fixed.
